# Website details
title: Zonweb News
description: Enjoy Simple News Site
avatar: /assets/image/avatar.png  # Periksa apakah path benar
author:
  name: hakerdefo
  url: https://github.com/hakerdefo

# Website URL and Base URL
url: https://www.viralhd.store  # URL domain utama
baseurl: ""  # Subdirektori tempat situs di-hosting

# Navigation links
navigation_links:
  - title: Blog
    url: https://www.viralhd.store/news  # Sesuaikan URL
  - title: About
    url: /news/about
  - title: Search
    url: /news/search

# Footer links
footer_links:
  - title: Privacy Policy
    url: /privacy-policy
  - title: Terms and Conditions
    url: /terms-and-conditions
  - title: Cookie Policy
    url: /cookie-policy
  - title: Contact US
    url: /contact

# Time zone
timezone: Asia/Kolkata

# Permalink
permalink: /:slug/  # Sesuai dengan pengaturan halaman pos

# Jekyll Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - webrick
  - jekyll-github-metadata

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME  # Pastikan file CNAME ada di root repositori

# Include robots.txt
include:
  - robots.txt

# Excerpt separator for content
excerpt_separator: <!--more-->
